# Project Euler
# Problem 2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms

# Use fibonacci number formula:
# Su, Francis E., et al. "Fibonacci Number Formula." Math Fun Facts.
# <http://www.math.hmc.edu/funfacts>.

from math import *
i = 1
sum = 0
a = 4000000
fib = 1

while fib <= a:
	fib = int(((1 + sqrt(5))**i - (1 - sqrt(5))**i) / (2**i * sqrt(5)))
	if fib%2 == 0:
		sum += fib
	i += 1

print(sum)

